# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SelectionCellWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cell_widget(object):
    def setupUi(self, cell_widget):
        cell_widget.setObjectName("cell_widget")
        cell_widget.resize(420, 50)
        self.gridLayout = QtWidgets.QGridLayout(cell_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.user_host_label = QtWidgets.QLabel(cell_widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.user_host_label.setFont(font)
        self.user_host_label.setScaledContents(False)
        self.user_host_label.setObjectName("user_host_label")
        self.gridLayout.addWidget(self.user_host_label, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(cell_widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(cell_widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(cell_widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(cell_widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)

        self.retranslateUi(cell_widget)
        QtCore.QMetaObject.connectSlotsByName(cell_widget)

    def retranslateUi(self, cell_widget):
        _translate = QtCore.QCoreApplication.translate
        cell_widget.setWindowTitle(_translate("cell_widget", "Form"))
        self.user_host_label.setText(_translate("cell_widget", "Username@hostname.de "))
        self.label.setText(_translate("cell_widget", "Queing System: Sun Grid Engine"))
        self.label_2.setText(_translate("cell_widget", "Queue: default"))
        self.label_3.setText(_translate("cell_widget", "CPU: 12"))
        self.label_4.setText(_translate("cell_widget", "Walltime: 07:00:00"))
